"""Phase 1 ITP stage: the only TRUSTED component.

A proof attempt is a Lean tactic script for a library theorem's exact
statement. Lean checks it against the precompiled library (lib/MegLib.olean
+ lib/Bridge.olean). An attempt only counts as proved if ALL of these hold:

  1. Lean reports no error.
  2. The attempt's elaborated statement is identical to the original
     theorem's (compared as Lean expressions, not as text).
  3. Leak guard: every library constant the proof term uses -- followed
     transitively through any auxiliary lemmas the tactics generated --
     comes strictly BEFORE the target in source order. The precompiled
     library contains all 999 theorems, so without this a proof could
     quietly cite the target itself or something proved from it.
  4. No `sorryAx` anywhere in the used constants.
"""
import os
import re
import subprocess
import tempfile

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LIB = os.path.join(ROOT, "lib")
LEAN = os.environ.get(
    "LEAN_BIN", "/home/yenat/lean4-toolchain/lean-4.34.0-linux/bin/lean")

BRIDGE = ("b_True, b_False, b_not, b_and, b_or, b_iff, b_eq, b_neq, b_ex")


def load_statements(meglib_path=os.path.join(LIB, "MegLib.lean")):
    """theorem name -> the exact signature text after the name, e.g.
    ' : (forall x1 : set, ...)'. Taken verbatim from the verified library so
    the attempt's statement is the library's statement, character for
    character."""
    sigs = {}
    for line in open(meglib_path, encoding="utf-8"):
        if not line.startswith("theorem "):
            continue
        rest = line[len("theorem "):]
        name, _, after = rest.partition(" ")
        sig = after.split(" := ", 1)[0]
        sigs[name] = " " + sig
    return sigs


_GUARD = r'''
open Lean in
#eval show CoreM Unit from do
  let env ← getEnv
  let some att := env.find? `Megalodon.{att} | IO.println "GUARD missing"
  let some orig := env.find? `Megalodon.{orig} | IO.println "GUARD noorig"
  IO.println s!"GUARD samestmt {att.type == orig.type}"
  -- transitive closure through constants defined in THIS file (auxiliary
  -- lemmas generated by tactics); library/core constants are leaves.
  let mut seen : NameSet := {}
  let mut todo : Array Name := #[`Megalodon.{att}]
  let mut used : Array Name := #[]
  while h : todo.size > 0 do
    let n := todo.back
    todo := todo.pop
    if seen.contains n then continue
    seen := seen.insert n
    let some ci := env.find? n | continue
    let isLocal := (env.getModuleIdxFor? n).isNone
    if !isLocal then
      used := used.push n
      continue
    for c in ci.type.getUsedConstants do todo := todo.push c
    if let some v := ci.value? (allowOpaque := true) then
      for c in v.getUsedConstants do todo := todo.push c
  IO.println s!"GUARD used {String.intercalate " " (used.toList.map toString)}"
'''


def check(target, statement_sig, tactic, timeout=60):
    """Run one attempt. Returns (ok, reason, used_constants)."""
    att = f"attempt__{re.sub(r'[^A-Za-z0-9_]', '_', target)}"
    src = (
        "import Lean\nimport Bridge\n"
        "set_option Elab.async false\nset_option maxRecDepth 8000\n"
        "set_option maxHeartbeats 400000\n"
        "set_option linter.unusedVariables false\n"
        "namespace Megalodon\n"
        f"theorem {att}{statement_sig} := by\n"
        + "".join(f"  {ln}\n" for ln in tactic.strip().splitlines())
        + "end Megalodon\n"
        + _GUARD.replace("{att}", att).replace("{orig}", target)
    )
    with tempfile.NamedTemporaryFile("w", suffix=".lean", delete=False,
                                     dir="/tmp") as fh:
        fh.write(src)
        path = fh.name
    try:
        r = subprocess.run([LEAN, path], capture_output=True, text=True,
                           timeout=timeout, env={**os.environ, "LEAN_PATH": LIB})
        out = r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        return False, "timeout", []
    finally:
        os.unlink(path)

    if re.search(r":\d+:\d+: error", out):
        first = next(l for l in out.splitlines() if ": error" in l)
        return False, "lean error: " + first.split(": error", 1)[1][:160], []
    m = re.search(r"GUARD samestmt (\w+)", out)
    if not m or m.group(1) != "true":
        return False, "statement mismatch", []
    m = re.search(r"GUARD used ?(.*)", out)
    used = m.group(1).split() if m else []
    if any(u == "sorryAx" for u in used):
        return False, "uses sorryAx", used
    return True, "ok", used


def leak_free(used, target_index, index_of):
    """Every library constant used must precede the target. Lean core and
    the bridge lemmas are always allowed."""
    for u in used:
        if not u.startswith("Megalodon."):
            continue
        short = u[len("Megalodon."):]
        if short.startswith("b_") or short == "set":
            continue
        i = index_of.get(short)
        if i is None:
            # auxiliary names like `Megalodon.and.eq_1` belong to their
            # parent declaration
            base = short.split(".")[0]
            i = index_of.get(base)
        if i is None or i >= target_index:
            return False, u
    return True, None
